name: Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: check nodejs version - must be ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build the admin Docker image
        run: | 
          docker build . --file admin-service/Dockerfile --tag mikamakusa/blog-test-admin-service:latest
          docker push mikamakusa/blog-test-admin-service:latest
      - name: Build the ads Docker image
        run: |
          docker build . --file ads-service/Dockerfile --tag mikamakusa/blog-test-ads-service:latest
          docker push mikamakusa/blog-test-ads-service:latest
      - name: Build the auth Docker image
        run: |
          docker build . --file auth-service/Dockerfile --tag mikamakusa/blog-test-auth-service:latest
          docker push mikamakusa/blog-test-auth-service:latest